package com.surovtsev.settingsscreen.viewmodel.helpers.typealiases

import com.surovtsev.core.viewmodel.EventReceiver
import com.surovtsev.settingsscreen.viewmodel.EventToSettingsScreenViewModel

typealias SettingsScreenEventReceiver = EventReceiver<EventToSettingsScreenViewModel>
