package com.surovtsev.settingsscreen.viewmodel.helpers.typealiases

import com.surovtsev.finitestatemachine.eventhandlerOld.EventHandlerOld
import com.surovtsev.settingsscreen.viewmodel.helpers.finitestatemachine.EventToSettingsScreenViewModel
import com.surovtsev.settingsscreen.viewmodel.helpers.finitestatemachine.SettingsScreenData

typealias SettingsScreenEventHandler = EventHandlerOld<EventToSettingsScreenViewModel, SettingsScreenData>
