package com.surovtsev.settingsscreen.viewmodel.helpers.typealiases

import com.surovtsev.finitestatemachine.FiniteStateMachine
import com.surovtsev.settingsscreen.viewmodel.helpers.finitestatemachine.EventToSettingsScreenViewModel
import com.surovtsev.settingsscreen.viewmodel.helpers.finitestatemachine.SettingsScreenData

typealias SettingsScreenFiniteStateMachine =
    FiniteStateMachine<EventToSettingsScreenViewModel, SettingsScreenData>
