package com.surovtsev.settingsscreen.viewmodel.helpers.typealiases

import com.surovtsev.core.viewmodel.ErrorDialogPlacer
import com.surovtsev.settingsscreen.viewmodel.EventToSettingsScreenViewModel
import com.surovtsev.settingsscreen.viewmodel.SettingsScreenData

typealias SettingsScreenErrorDialogPlacer = ErrorDialogPlacer<EventToSettingsScreenViewModel, SettingsScreenData>
