package com.surovtsev.settingsscreen.viewmodel.helpers.typealiases

import com.surovtsev.core.viewmodel.FiniteStateMachineFactory
import com.surovtsev.settingsscreen.viewmodel.helpers.finitestatemachine.EventToSettingsScreenViewModel
import com.surovtsev.settingsscreen.viewmodel.helpers.finitestatemachine.SettingsScreenData

typealias SettingsScreenFiniteStateMachineFactory =
    FiniteStateMachineFactory<EventToSettingsScreenViewModel, SettingsScreenData>
