package com.surovtsev.settingsscreen.viewmodel.helpers.typealiases

import com.surovtsev.finitestatemachine.helpers.EventReceiver
import com.surovtsev.settingsscreen.viewmodel.helpers.finitestatemachine.EventToSettingsScreenViewModel

typealias SettingsScreenEventReceiver = EventReceiver<EventToSettingsScreenViewModel>
