package com.surovtsev.rankingscreen.rankinscreenviewmodel.helpers.typealiases

import com.surovtsev.core.viewmodel.ScreenStateFlow
import com.surovtsev.rankingscreen.rankinscreenviewmodel.helpers.finitestatemachine.RankingScreenData

typealias RankingScreenStateFlow = ScreenStateFlow<RankingScreenData>
