package com.surovtsev.rankingscreen.rankinscreenviewmodel.helpers.typealiases

import com.surovtsev.core.viewmodel.EventReceiver
import com.surovtsev.rankingscreen.rankinscreenviewmodel.EventToRankingScreenViewModel

typealias RankingScreenEventReceiver = EventReceiver<EventToRankingScreenViewModel>
