package com.surovtsev.rankingscreen.rankinscreenviewmodel.helpers.typealiases

import com.surovtsev.finitestatemachine.helpers.EventReceiver
import com.surovtsev.rankingscreen.rankinscreenviewmodel.helpers.finitestatemachine.EventToRankingScreenViewModel

typealias RankingScreenEventReceiver = EventReceiver<EventToRankingScreenViewModel>
