package com.surovtsev.rankingscreen.rankinscreenviewmodel.helpers.typealiases

import com.surovtsev.finitestatemachine.stateholder.StateHolder
import com.surovtsev.rankingscreen.rankinscreenviewmodel.helpers.finitestatemachine.RankingScreenData


typealias RankingScreenStateHolder = StateHolder<RankingScreenData>
